# Generated by Django 4.0.2 on 2022-02-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, null=True, unique=True)),
                ('description', models.TextField()),
                ('skils', models.CharField(max_length=100)),
                ('skils1', models.CharField(max_length=100)),
                ('skils2', models.CharField(max_length=100)),
                ('skils3', models.CharField(max_length=100)),
                ('skils4', models.CharField(max_length=100)),
                ('skils5', models.CharField(max_length=100)),
                ('skils6', models.CharField(max_length=100)),
                ('skils7', models.CharField(max_length=100)),
                ('skils8', models.CharField(max_length=100)),
                ('skils9', models.CharField(max_length=100)),
                ('skils10', models.CharField(max_length=100)),
                ('skils11', models.CharField(max_length=100)),
                ('skils12', models.CharField(max_length=100)),
            ],
        ),
    ]
