# Generated by Django 4.0.2 on 2022-02-28 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_alter_info_skils_alter_info_skils1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='skils1',
        ),
        migrations.RemoveField(
            model_name='info',
            name='skils10',
        ),
        migrations.RemoveField(
            model_name='info',
            name='skils11',
        ),
        migrations.RemoveField(
            model_name='info',
            name='skils12',
        ),
        migrations.RemoveField(
            model_name='info',
            name='skils2',
        ),
        migrations.RemoveField(
            model_name='info',
            name='skils3',
        ),
        migrations.RemoveField(
            model_name='info',
            name='skils4',
        ),
        migrations.RemoveField(
            model_name='info',
            name='skils5',
        ),
        migrations.RemoveField(
            model_name='info',
            name='skils6',
        ),
        migrations.RemoveField(
            model_name='info',
            name='skils7',
        ),
        migrations.RemoveField(
            model_name='info',
            name='skils8',
        ),
        migrations.RemoveField(
            model_name='info',
            name='skils9',
        ),
    ]
