# Generated by Django 4.0.2 on 2022-02-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_remove_info_skils1_remove_info_skils10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='skils',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
