# Generated by Django 4.0.2 on 2022-02-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_alter_info_skils'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='skils',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
